export const artworks = [
  '/assets/images/artworks/1_cyber_woman.jpg',
  '/assets/images/artworks/2_zoom_people.jpg',
  '/assets/images/artworks/3_androids_humanoid_robots_cyborgs_dream_with_electric sheep.jpg',
  '/assets/images/artworks/4_boy_sourrounded_by_smartphones.jpg',
  '/assets/images/artworks/5_windows labyrinth.jpg',
  '/assets/images/artworks/6_computer_broke_with_a _eyboard_in_the_screen_flying_in the_middle_of_computers.jpg',
  '/assets/images/artworks/7_metal_cyber_angels.jpg',
  '/assets/images/artworks/8_cyber_city.jpg',
  '/assets/images/artworks/9_man_with_grey_coat_and_black_hat_with_a_cellphone_in_the_mouth.jpg',
  '/assets/images/artworks/10_smartphone_two_legs_walking_on_water.jpg',
  '/assets/images/artworks/11_person_smartphone_hug.jpg',
  '/assets/images/artworks/12_surveillance_camera_flower_with_lightning.jpg',
  '/assets/images/artworks/13_selfie_aliens.jpg',
  '/assets/images/artworks/14_cyborg_earthtree.jpg',
  '/assets/images/artworks/15_computer_in_flames.jpg',
  '/assets/images/artworks/16_robot_humans_nature.jpg',
  '/assets/images/artworks/17_robot_family_hugging.jpg',
  '/assets/images/artworks/18_windows95_start_to_a_golden_fantastic_land_with_a_glitter_baby_blue_sky_with_clouds.jpg',
  '/assets/images/artworks/19_three_face_smartphone_people.jpg',
  '/assets/images/artworks/20_woman_holding_gun_to_head_with_computer.jpg',
  '/assets/images/artworks/21_selfie_stick_robot.jpg',
  '/assets/images/artworks/22_4_leg_smartphone_dog.jpg',
  '/assets/images/artworks/23_mountain_of_cellphones_with_iridiscent_snow_around.jpg',
  '/assets/images/artworks/24_silver_robots_kissing.jpg',
  '/assets/images/artworks/25_stock_market_jungle.jpg',
  '/assets/images/artworks/26_plant_human.jpg',
  '/assets/images/artworks/27_microchip_nature.jpg',
  '/assets/images/artworks/28_human_stranded_in_circuit_island_.jpg',
  '/assets/images/artworks/29_rollercoaster.jpg',
  '/assets/images/artworks/30_blue_Internet_explorer_logo_with_golden_wings_flying_and_white lights.jpg',
  '/assets/images/artworks/31_flying_computers_blue_sky.jpg',
  '/assets/images/artworks/32_hand-touch-world.jpg',
  '/assets/images/artworks/33_computer tower_in_white_silver_glitter mountain.jpg',
  '/assets/images/artworks/34_robot_meditation.jpg',
  '/assets/images/artworks/35_robot_plants.jpg',
  '/assets/images/artworks/36_smartphone_tree_city.jpg',
  '/assets/images/artworks/37_person_in_nature_computer.jpg',
  '/assets/images/artworks/38_stonehenge_smartphone.jpg',
  '/assets/images/artworks/39_brain_computer_farm.jpg',
  '/assets/images/artworks/40_cyber_city_flag.jpg',
  '/assets/images/artworks/41_clones_laboratory.jpg',
  '/assets/images/artworks/42_robot_tv_lights_plant.jpg',
  '/assets/images/artworks/43_iridiscent_green_land_with_baby_blue_sky.jpg',
  '/assets/images/artworks/44_blue keyboward.jpg',
  '/assets/images/artworks/45_light_blue_thin cable lights_with laptops.jpg',
  '/assets/images/artworks/46_robot-hug.jpg',
  '/assets/images/artworks/47_social-media-city.jpg',
  '/assets/images/artworks/48_robots_with_ads.jpg',
  '/assets/images/artworks/49_flowers field_with dark_smartphones_growing.jpg',
  '/assets/images/artworks/50_dream_tv_machine_in_bushes.jpg',
  '/assets/images/artworks/51_matrix_forest.jpg',
  '/assets/images/artworks/52_stock_market_forest.jpg',
  '/assets/images/artworks/53_cyborg_dolphins_city_underwater.jpg',
  '/assets/images/artworks/54_weird_machine_floating_with_blue_lights_rising_up.jpg',
  '/assets/images/artworks/55_xray_blue_robot_in_fantasy_enviroment.jpg',
  '/assets/images/artworks/56_computer_in_the_darkness lights_around_with_white_cable_lights_coming_out.jpg',
  '/assets/images/artworks/57_city_ads.jpg',
  '/assets/images/artworks/58_cyber_dog.jpg',
  '/assets/images/artworks/59_cyborgs_a_fictional_being_that is_human_robot_with_cables.jpg',
  '/assets/images/artworks/60_suit_camera_person.jpg',
  '/assets/images/artworks/61_keyboard_over_man_with_arms_and_computer_head.jpg',
  '/assets/images/artworks/62_code_with_a_floating_silver_robot_face_with_bright_pink_sky_and_black_palms.jpg',
  '/assets/images/artworks/63_robotic_unicorn_tornado.jpg',
  '/assets/images/artworks/64_social_media_cake.jpg',
  '/assets/images/artworks/65_bitcoin_xray_head_brain.jpg',
  '/assets/images/artworks/66_computers around_sexy robot.jpg',
  '/assets/images/artworks/68_rusty_computers_with_green_letters_inside_the_screen.jpg',
  '/assets/images/artworks/69_computer_river_waves.jpg',
  '/assets/images/artworks/71_alien_god_faces_eyes_in_desert.jpg',
  '/assets/images/artworks/72_squared_rusty_robot_in_landscape.jpg',
  '/assets/images/artworks/73_android_robot_head.jpg',
  '/assets/images/artworks/74_flying_golden_cross_converting_into_a_smartphone.jpg',
  '/assets/images/artworks/75_smartphone_interdimensional_doors.jpg',
  '/assets/images/artworks/76_person_with_head_inside_a_computer_screen.jpg',
  '/assets/images/artworks/78_robot flowers.jpg',
  '/assets/images/artworks/79_cyber_gamer.jpg',
];
